version : '3.8'

volumes:
  mysql_data:
networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@2002
      MYSQL_DATABASE: pharmacy_management
      MYSQL_USER: userDB
      MYSQL_PASSWORD: yassir@2002
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-boot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 3s
      timeout: 30s
  pharmacy_management:
    build : .
    ports:
      - "8083:8083"
    depends_on:
       mysql:
         condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASCOURCE_URL=jdbc:mysql://mysql:3306/pharmacy_management
      - SPRING_DATASOURCE_USERNAME=userDB
      - SPRING_DATASOURCE_PASSWORD=yassir@2002
    networks:
        - spring-boot-mysql-network
